import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import joblib
import os

def main():
    # 1. Setup Models Directory
    os.makedirs("models", exist_ok=True)
    
    # Paths to the datasets
    # These datasets were created by the user in the top level project directory
    datasets_dir = r"c:\Users\Sugan\Music\project\datasets"
    
    # -----------------------------------------------------
    # 2. Train General Symptom Model (RandomForest)
    # -----------------------------------------------------
    print("Loading Training.csv for General Symptom Diagnosis...")
    symptom_path = os.path.join(datasets_dir, "Training.csv")
    df_symp = pd.read_csv(symptom_path)
    
    # The last column is 'prognosis' (the disease). The other columns are symptoms.
    # Note: Some rows might have an extra unnamed column. Drop if necessary.
    X_symp = df_symp.drop(columns=["prognosis"])
    # If there's a purely empty column (often generated by pandas trailing commas), drop it
    X_symp = X_symp.dropna(axis=1, how='all')
    
    y_symp = df_symp["prognosis"]
    
    print("Training Symptom Model (RandomForest)...")
    rf_symp = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf_symp.fit(X_symp, y_symp)
    
    # Save model and feature list for ML predictions
    joblib.dump(rf_symp, "models/symptom_model.joblib")
    joblib.dump(list(X_symp.columns), "models/symptom_features.joblib")
    print("Saved models/symptom_model.joblib")

    # -----------------------------------------------------
    # 3. Train Heart Disease Model (XGBoost)
    # -----------------------------------------------------
    print("\nLoading Heart Disease dataset...")
    heart_path = os.path.join(datasets_dir, "heart_disease_health_indicators_BRFSS2015.csv")
    df_heart = pd.read_csv(heart_path)
    
    # Target column is HeartDiseaseorAttack
    X_heart = df_heart.drop(columns=["HeartDiseaseorAttack"])
    y_heart = df_heart["HeartDiseaseorAttack"]
    
    print("Training Heart Disease Model (XGBoost)...")
    xgb_heart = xgb.XGBClassifier(eval_metric='logloss', n_jobs=-1, random_state=42)
    xgb_heart.fit(X_heart, y_heart)
    
    # Save model and features
    joblib.dump(xgb_heart, "models/heart_model.joblib")
    joblib.dump(list(X_heart.columns), "models/heart_features.joblib")
    print("Saved models/heart_model.joblib")

    # -----------------------------------------------------
    # 4. Train Diabetes Risk Model (XGBoost)
    # -----------------------------------------------------
    print("\nLoading Diabetes dataset...")
    diabetes_path = os.path.join(datasets_dir, "diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
    df_diab = pd.read_csv(diabetes_path)
    
    target_col = "Diabetes_binary"
    if target_col not in df_diab.columns:
        print("Could not find Diabetes_binary column. Using alternative...")
        target_col = df_diab.columns[0] # Usually the first column is target
        
    X_diab = df_diab.drop(columns=[target_col])
    y_diab = df_diab[target_col]
    
    print("Training Diabetes Model (XGBoost)...")
    xgb_diab = xgb.XGBClassifier(eval_metric='logloss', n_jobs=-1, random_state=42)
    xgb_diab.fit(X_diab, y_diab)
    
    joblib.dump(xgb_diab, "models/diabetes_model.joblib")
    joblib.dump(list(X_diab.columns), "models/diabetes_features.joblib")
    print("Saved models/diabetes_model.joblib")
    
    print("\n✅ All models trained and saved to backend/models/ successfully!")

if __name__ == "__main__":
    main()
